# Generated by Django 6.0.6 on 2026-06-25 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.CharField(choices=[('in progress', 'В обробці'), ('successful', 'Успішно'), ('error', 'Помилка'), ('refund', 'Повернення коштів')], default='in progress', max_length=20)),
                ('payment_method', models.CharField(choices=[('Corporate card', 'Корпоративна картка'), ('Bank transfer', 'Банківський переказ за реквізитами')], default='Bank transfer', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='invoice.invoice')),
            ],
        ),
    ]
