# Generated by Django 6.0.6 on 2026-06-28 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='invoice',
        ),
    ]
