# Generated by Django 6.0.6 on 2026-06-28 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_booking_invoice'),
        ('invoice', '0001_initial'),
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='booking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='bookings.booking'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='spaces.organization'),
        ),
    ]
