# Generated by Django 6.0.6 on 2026-06-29 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_invoice_booking_alter_invoice_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='booking',
        ),
    ]
